# Generated by Django 3.1.1 on 2021-02-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('campusId', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('campusName', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
            ],
            options={
                'db_table': 'campus',
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('cid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('ccredit', models.IntegerField()),
                ('ctype', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('deptId', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.campus')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='studentAcademicDetails',
            fields=[
                ('sid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=8)),
                ('dob', models.DateField()),
                ('y_o_reg', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
                ('deptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.department')),
            ],
            options={
                'db_table': 'academic_details',
            },
        ),
        migrations.CreateModel(
            name='studentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
                ('stdReg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='felony.studentacademicdetails')),
            ],
            options={
                'db_table': 'student_registration',
            },
        ),
        migrations.CreateModel(
            name='student_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.studentacademicdetails')),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
        migrations.CreateModel(
            name='profRegistration',
            fields=[
                ('pfRegId', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
                ('deptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.department')),
            ],
            options={
                'db_table': 'prof_registration',
            },
        ),
        migrations.CreateModel(
            name='prof_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.course')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.profregistration')),
            ],
            options={
                'db_table': 'prof_course',
            },
        ),
        migrations.CreateModel(
            name='examenroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.course')),
                ('profId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.profregistration')),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='department_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.CharField(default='Y', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felony.department')),
            ],
            options={
                'db_table': 'department_course',
            },
        ),
    ]
